name: Prove blocks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
    prove:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                prover: [risc0]
        defaults:
            run:
                working-directory: provers/${{ matrix.prover }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - run: rustup toolchain install stable --profile minimal

            - uses: Swatinem/rust-cache@v2

            - name: Setup
              run: make setup
              shell: bash

            - name: Prove
              run: make prove
              shell: bash